params:
  hidden_layer_sizes:
    - [32,]
    - [64,]
    - [128,]
    - [256,]
    - [512,]
    - [32, 32,]
    - [64, 64,]
    - [128, 128,]
    - [256, 256,]
    - [512, 512,]
  activation:
    - "logistic"
    - "tanh"
    - "relu"
plots:
    x: param_clf__hidden_layer_sizes
    y: mean_test_f1_weighted
    style: param_clf__activation
