params:
  kernel:
    - "poly"
    - "rbf"
  C:
    - 1.e-4
    - 1.e-3
    - 1.e-2
    - 1.e-1
    - 1.e-0
    - 1.e+1
plots:
    x: param_clf__C
    y: mean_test_f1_weighted
    style: param_clf__kernel
log: true